name: winglt
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.3
  modal_progress_hud_nsn: ^0.5.1
  cloud_firestore: ^4.15.3
  animated_text_kit: ^4.2.2
  awesome_snackbar_content: ^0.1.3
  google_sign_in: ^6.2.1
  firebase_storage: ^11.6.9
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  firebase_app_check: ^0.2.1+17
  pinput: ^4.0.0
  local_auth: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/bubbles.svg
    - assets/Google.svg
    - assets/profile.jpg

  fonts:
    - family: MyCustomFont
      fonts:
        - asset: assets/fonts/ProtestGuerrilla-Regular.ttf
          weight: 400
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
