// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const String temp = 'AIzaSyBVUIbQIONU0rfVmJHt00qCLstkZQfJIu0';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: temp,
    appId: '1:848483650186:web:8c184ee38e16dd2be77b73',
    messagingSenderId: '848483650186',
    projectId: 'buzzchat-f8318',
    authDomain: 'buzzchat-f8318.firebaseapp.com',
    storageBucket: 'buzzchat-f8318.appspot.com',
    measurementId: 'G-SXZKSLSCM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'temp',
    appId: '1:848483650186:android:26e9a94b7b0411a1e77b73',
    messagingSenderId: '848483650186',
    projectId: 'buzzchat-f8318',
    storageBucket: 'buzzchat-f8318.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: temp,
    appId: '1:848483650186:ios:75eeaf507061d1bce77b73',
    messagingSenderId: '848483650186',
    projectId: 'buzzchat-f8318',
    storageBucket: 'buzzchat-f8318.appspot.com',
    iosBundleId: 'com.example.buzzChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: temp,
    appId: '1:848483650186:ios:230dac16a7559aa8e77b73',
    messagingSenderId: '848483650186',
    projectId: 'buzzchat-f8318',
    storageBucket: 'buzzchat-f8318.appspot.com',
    iosBundleId: 'com.example.buzzChat.RunnerTests',
  );
}
